from flask import request, json, render_template
from datetime import datetime

from sqlalchemy.sql import text
from app import app, db
from models.data import HardwareState, ChannelType, ConnectionType, TractType, ChannelState, ChannelIniciator, \
    DiagnosticParams, TractState, UserState, ErrorChannel, Report, RowReports, Tracts, ReserveTracts

import app_logger

logger = app_logger.get_logger(__name__)

@app.route("/api/v1/utils/insert_stable_data", methods=['GET'])
def insert():
    try:
        # table 3
        temp = HardwareState('Норма')
        db.session.add(temp)

        temp = HardwareState('Ошибка')
        db.session.add(temp)

        temp = HardwareState('Предупреждение')
        db.session.add(temp)

        temp = HardwareState('Неизвестное')
        db.session.add(temp)


        #table 4

        temp = ChannelType('ТЧ')
        db.session.add(temp)

        temp = ChannelType('ТЛГ')
        db.session.add(temp)

        temp = ChannelType('ОЦК')
        db.session.add(temp)

        temp = ChannelType('АЦК')
        db.session.add(temp)

        temp = ChannelType('Ethernet')
        db.session.add(temp)

        temp = ChannelType('Неопределен')
        db.session.add(temp)

        #table 5
        temp = ConnectionType('Фиксированное')
        db.session.add(temp)

        temp = ConnectionType('Оперативное')
        db.session.add(temp)

        #table 6
        temp = TractType('E1')
        db.session.add(temp)

        temp = TractType('STM')
        db.session.add(temp)

        temp = TractType('Ethernet')
        db.session.add(temp)

        temp = TractType('CWDM')
        db.session.add(temp)

        temp = TractType('Радиорелейный тракт')
        db.session.add(temp)


        #table 7
        temp = ChannelState('Не создан')
        db.session.add(temp)

        temp = ChannelState('В процессе создания')
        db.session.add(temp)

        temp = ChannelState('Норма')
        db.session.add(temp)

        temp = ChannelState('Несрочная авария')
        db.session.add(temp)

        temp = ChannelState('Срочная авария')
        db.session.add(temp)

        temp = ChannelState('Восстановлен')
        db.session.add(temp)

        temp = ChannelState('Удален без восстановления')
        db.session.add(temp)

        temp = ChannelState('Удален, ожидает восстановления')
        db.session.add(temp)

        temp = ChannelState('На диагностике')
        db.session.add(temp)

        #table 8
        temp = ChannelIniciator('Оператор КАУС')
        db.session.add(temp)

        temp = ChannelIniciator('Система управления КСК или оператор РМО')
        db.session.add(temp)

        temp = ChannelIniciator('Встречный КАУС')
        db.session.add(temp)


        #table 9
        temp = DiagnosticParams('Уровень принимаемого сигнала', 'дБ', 'float', 'rssi')
        db.session.add(temp)

        temp = DiagnosticParams('Затухание сигнала', 'дБ', 'float', 'dB')
        db.session.add(temp)

        temp = DiagnosticParams('Уровень шума', 'дБ', 'float', 'SNR')
        db.session.add(temp)

        temp = DiagnosticParams('Коэффициент битовых ошибок', '', 'float', 'BER')
        db.session.add(temp)

        temp = DiagnosticParams('Реальная пропускная способность для пакетов данных', 'Мбайт/с', 'int', 'BPS')
        db.session.add(temp)

        temp = DiagnosticParams('Среднее время приема-передачи пакетов данных', 'мс', 'int', 'RTT')
        db.session.add(temp)

        temp = DiagnosticParams('Уровень джиттера', 'мс', 'int', 'jitter')
        db.session.add(temp)

        temp = DiagnosticParams('Время готовности', 'сек', 'int', 'AS')
        db.session.add(temp)

        temp = DiagnosticParams('Процент времени готовности', '%', 'int', 'ASR')
        db.session.add(temp)

        temp = DiagnosticParams('Время неготовности', 'сек', 'int', 'AUS')
        db.session.add(temp)

        temp = DiagnosticParams('Процент неготовности', '%', 'int', 'USR')
        db.session.add(temp)

        temp = DiagnosticParams('Длительность поражения сигнала ошибками', 'сек', 'int', 'ES')
        db.session.add(temp)

        temp = DiagnosticParams('Процент длительности поражения сигнала ошибками', '%', 'int', 'ESR')
        db.session.add(temp)

        temp = DiagnosticParams('Время, свободное от ошибок', 'сек', 'int', 'EFS')
        db.session.add(temp)

        temp = DiagnosticParams('Процент времени, свободного от ошибок', '%', 'int', 'EFSR')
        db.session.add(temp)

        temp = DiagnosticParams('Длительность многократного поражения ошибками', 'сек', 'int', 'SES')
        db.session.add(temp)

        temp = DiagnosticParams('Процент длительность многократного поражения ошибками', '%', 'int', 'SESR')
        db.session.add(temp)

        temp = DiagnosticParams('Число ошибочных блоков', '', 'int', 'ЕВ')
        db.session.add(temp)

        temp = DiagnosticParams('Число блоков с фоновой ошибкой', '', 'int', 'ВВЕ')
        db.session.add(temp)

        temp = DiagnosticParams('Процент числа блоков с фоновой ошибкой', '%', 'int', 'ВВЕR')
        db.session.add(temp)

        temp = DiagnosticParams('Частота блоковых ошибок', '', 'float', 'BLER')
        db.session.add(temp)

        # table 10
        temp = TractState('Тракт не организова')
        db.session.add(temp)

        temp = TractState('Тракт в процессе организации')
        db.session.add(temp)

        temp = TractState('Тракт организован')
        db.session.add(temp)

        temp = TractState('Авария несрочная')
        db.session.add(temp)

        temp = TractState('Авария срочная')
        db.session.add(temp)

        #table 11
        temp = UserState('Cвязь в процессе организации')
        db.session.add(temp)

        temp = UserState('Cвязь организована')
        db.session.add(temp)

        temp = UserState('Ожидает восстановления')
        db.session.add(temp)


        #table 11
        temp = ErrorChannel('В сети КСК отсутствуют свободные ресурсы')
        db.session.add(temp)

        temp = ErrorChannel('Отказ оборудования')
        db.session.add(temp)

        temp = ErrorChannel('Другая причина')
        db.session.add(temp)



        db.session.commit()


        #report 1
        report = Report('tracts', 'default')
        db.session.add(report)
        db.session.flush()

        row = RowReports('id',   '#', report.id)
        db.session.add(row)

        row = RowReports('name',   'Наименование', report.id)
        db.session.add(row)

        row = RowReports('state',  'Статус', report.id)
        db.session.add(row)

        row = RowReports('type',   'Тип', report.id)
        db.session.add(row)

        row = RowReports('hard_from', 'Сторона А', report.id)
        db.session.add(row)

        row = RowReports('hard_to',   'Сторона Б', report.id)
        db.session.add(row)

        row = RowReports('reserve',   'Резервные\основные тракты', report.id)
        db.session.add(row)

        row = RowReports('params',   'Параметры качества', report.id)
        db.session.add(row)

        row = RowReports('damage',   'Повреждения линии', report.id)
        db.session.add(row)
        row = RowReports('channels',   'Приложенные каналы', report.id)
        db.session.add(row)

        #report 2
        report = Report('channel', 'default')
        db.session.add(report)
        db.session.flush()

        row = RowReports('id',   '#', report.id)
        db.session.add(row)
        row = RowReports('name',   'Наименование', report.id)
        db.session.add(row)
        row = RowReports('comment',   'Комментарий ', report.id)
        db.session.add(row)
        row = RowReports('state',   'Статус', report.id)
        db.session.add(row)
        row = RowReports('last_change_state',   'Последнее изменение', report.id)
        db.session.add(row)

        db.session.commit()

        reservDict = {}

        tract = Tracts('1.1', 'E1', '', 1, datetime.now(), 'A1/15', 'A4/3', '1', '1')
        db.session.add(tract)
        db.session.flush()
        tract = Tracts('1.2', 'E1', '', 1, datetime.now(), 'A1/16', 'A4/4', '1', '1')
        db.session.add(tract)
        db.session.flush()
        tract = Tracts('1.3', 'E1', '', 1, datetime.now(), 'A1/15', 'A3/3', '2', '1')
        db.session.add(tract)
        db.session.flush()
        tract = Tracts('1.4', 'E1', '', 1, datetime.now(), 'A1/16', 'A3/4', '2', '1')
        db.session.add(tract)
        db.session.flush()
        tract = Tracts('1.5', 'E1', '', 1, datetime.now(), 'A2/15', 'A4/3', '1', '2')
        db.session.add(tract)
        db.session.flush()
        tract = Tracts('1.6', 'E1', '', 1, datetime.now(), 'A2/16', 'A4/4', '1', '2')
        db.session.add(tract)
        db.session.flush()
        tract = Tracts('1.7', 'E1', '', 1, datetime.now(), 'A2/15', 'A3/3', '2', '2')
        db.session.add(tract)
        db.session.flush()
        tract = Tracts('1.8', 'E1', '', 1, datetime.now(), 'A2/16', 'A3/4', '2', '2')
        db.session.add(tract)
        db.session.flush()
        tract = Tracts('1.9', 'Ethernet', '', 1, datetime.now(), 'A5', 'A6', '25', '25')
        db.session.add(tract)
        db.session.flush()
        tract = Tracts('1.10', 'Ethernet', '', 1, datetime.now(), 'A5', 'A6', '26', '26')
        db.session.add(tract)
        db.session.flush()
        tract = Tracts('1.11', 'Ethernet', '', 1, datetime.now(), 'A6', 'A7.1', '1', '1')
        db.session.add(tract)
        db.session.flush()
        reservDict['1.11'] = tract.id
        tract = Tracts('1.12', 'Ethernet', '', 1, datetime.now(), 'A6', 'A8.1', '2', '1')
        db.session.add(tract)
        db.session.flush()
        reservDict['1.12'] = tract.id
        reserv = ReserveTracts(reservDict['1.11'], reservDict['1.12'])
        db.session.add(reserv)
        tract = Tracts('1.13', 'Ethernet', '', 1, datetime.now(), 'A6', 'A9/1', '3', '1')
        db.session.add(tract)
        db.session.flush()
        reservDict['1.13'] = tract.id
        tract = Tracts('1.14', 'Ethernet', '', 1, datetime.now(), 'A6', 'A10/1', '4', '1')
        db.session.add(tract)
        db.session.flush()
        reservDict['1.14'] = tract.id
        reserv = ReserveTracts(reservDict['1.13'], reservDict['1.14'])
        db.session.add(reserv)
        tract = Tracts('1.15', 'E1', '', 1, datetime.now(), 'A4/7', 'A7.1', '1', '2')
        db.session.add(tract)
        db.session.flush()
        reservDict['1.15'] = tract.id
        tract = Tracts('1.16', 'E1', '', 1, datetime.now(), 'A4/7', 'A8.1', '2', '2')
        db.session.add(tract)
        db.session.flush()
        reservDict['1.16'] = tract.id
        reserv = ReserveTracts(reservDict['1.15'], reservDict['1.16'])
        db.session.add(reserv)
        tract = Tracts('1.17', 'E1', '', 1, datetime.now(), 'A4/7', 'A9/1', '3', '2')
        db.session.add(tract)
        db.session.flush()
        reservDict['1.17'] = tract.id
        tract = Tracts('1.18', 'E1', '', 1, datetime.now(), 'A4/7', 'A10/1', '4', '2')
        db.session.add(tract)
        db.session.flush()
        reservDict['1.18'] = tract.id
        reserv = ReserveTracts(reservDict['1.17'], reservDict['1.18'])
        db.session.add(reserv)
        tract = Tracts('1.19', 'E1', '', 1, datetime.now(), 'A4/8', 'A7.1', '1', '3')
        db.session.add(tract)
        db.session.flush()
        reservDict['1.19'] = tract.id
        tract = Tracts('1.20', 'E1', '', 1, datetime.now(), 'A4/8', 'A8.1', '2', '3')
        db.session.add(tract)
        db.session.flush()
        reservDict['1.20'] = tract.id
        reserv = ReserveTracts(reservDict['1.19'], reservDict['1.20'])
        db.session.add(reserv)
        tract = Tracts('1.21', 'E1', '', 1, datetime.now(), 'A4/8', 'A9.1', '3', '3')
        db.session.add(tract)
        db.session.flush()
        reservDict['1.21'] = tract.id
        tract = Tracts('1.22', 'E1', '', 1, datetime.now(), 'A4/8', 'A10.1', '4', '3')
        db.session.add(tract)
        db.session.flush()
        reservDict['1.22'] = tract.id
        reserv = ReserveTracts(reservDict['1.21'], reservDict['1.22'])
        db.session.add(reserv)
        tract = Tracts('1.23', 'DWDM', '', 1, datetime.now(), 'A7.1', 'A7.2/1', 'Линия', 'Общий')
        db.session.add(tract)
        db.session.flush()
        tract = Tracts('1.24', 'DWDM', '', 1, datetime.now(), 'A8.1', 'A8.2/1', 'Линия', 'Общий')
        db.session.add(tract)
        db.session.flush()
        tract = Tracts('1.25+1.909+1.910+1.323', 'DWDM', '', 1, datetime.now(), 'A9/4', 'A56/4', 'Вх/Вых', 'Вх/Вых')
        db.session.add(tract)
        db.session.flush()
        tract = Tracts('1.26+1.911+1.324', 'DWDM', '', 1, datetime.now(), 'A10/1', 'A57/1', 'Вх/Вых', 'Линия')
        db.session.add(tract)
        db.session.flush()
        tract = Tracts('1.27+1.901+1.241', 'DWDM', '', 1, datetime.now(), 'A7.2/1', 'A38.2/1', '1', '1')
        db.session.add(tract)
        db.session.flush()
        reservDict['1.27+1.901+1.241'] = tract.id
        tract = Tracts('1.28+1.902+1.242', 'DWDM', '', 1, datetime.now(), 'A7.2/1', 'A38.2/1', '2', '2')
        db.session.add(tract)
        db.session.flush()
        reservDict['1.28+1.902+1.242'] = tract.id
        reserv = ReserveTracts(reservDict['1.27+1.901+1.241'], reservDict['1.28+1.902+1.242'])
        db.session.add(reserv)
        tract = Tracts('1.29+1.903+1.243', 'DWDM', '', 1, datetime.now(), 'A7.1/1', 'A38.2/1', '3', '3')
        db.session.add(tract)
        db.session.flush()
        reservDict['1.29+1.903+1.243'] = tract.id
        reserv = ReserveTracts(reservDict['1.27+1.901+1.241'], reservDict['1.29+1.903+1.243'])
        db.session.add(reserv)
        tract = Tracts('1.30+1.904+1.244', 'DWDM', '', 1, datetime.now(), 'A7.2/1', 'A38.2/1', '4', '4')
        db.session.add(tract)
        db.session.flush()
        reservDict['1.30+1.904+1.244'] = tract.id
        reserv = ReserveTracts(reservDict['1.27+1.901+1.241'], reservDict['1.30+1.904+1.244'])
        db.session.add(reserv)
        tract = Tracts('1.31+1,905+1,245', 'DWDM', '', 1, datetime.now(), 'A8.2/1', 'A39.2/1', '1', '1')
        db.session.add(tract)
        db.session.flush()
        reservDict['1.31+1,905+1,245'] = tract.id
        tract = Tracts('1.32+1.906+1.246', 'DWDM', '', 1, datetime.now(), 'A8.2/1', 'A39.2/1', '2', '2')
        db.session.add(tract)
        db.session.flush()
        reservDict['1.32+1.906+1.246'] = tract.id
        reserv = ReserveTracts(reservDict['1.31+1,905+1,245'], reservDict['1.32+1.906+1.246'])
        db.session.add(reserv)
        tract = Tracts('1.33+1.907+1.247', 'DWDM', '', 1, datetime.now(), 'A8.2/1', 'A39.2/1', '3', '3')
        db.session.add(tract)
        db.session.flush()
        reservDict['1.33+1.907+1.247'] = tract.id
        reserv = ReserveTracts(reservDict['1.31+1,905+1,245'], reservDict['1.33+1.907+1.247'])
        db.session.add(reserv)
        tract = Tracts('1.34+1.908+1.248', 'DWDM', '', 1, datetime.now(), 'A8.2/1', 'A39.2/1', '4', '4')
        db.session.add(tract)
        db.session.flush()
        reservDict['1.34+1.908+1.248'] = tract.id
        reserv = ReserveTracts(reservDict['1.31+1,905+1,245'], reservDict['1.34+1.908+1.248'])
        db.session.add(reserv)
        tract = Tracts('1.35', 'E1', '', 1, datetime.now(), 'A109/16', 'A7.1', '1', '7')
        db.session.add(tract)
        db.session.flush()
        tract = Tracts('1.36', 'E2', '', 1, datetime.now(), 'A102/3', 'A7.1', 'SFP1', '8')
        db.session.add(tract)
        db.session.flush()
        tract = Tracts('1.40', 'Ethernet', '', 1, datetime.now(), 'A102/1', 'A101', '10', 'П1')
        db.session.add(tract)
        db.session.flush()
        tract = Tracts('1.41', 'Ethernet', '', 1, datetime.now(), 'A102/2', 'A101', '10', 'П2')
        db.session.add(tract)
        db.session.flush()
        tract = Tracts('1.42', 'E3', '', 1, datetime.now(), 'A102/2', 'A102/4', '14', 'SFP22')
        db.session.add(tract)
        db.session.flush()
        tract = Tracts('1.43+1.936+1.711', 'DWDM', '', 1, datetime.now(), 'A102/1', 'A104', 'Линия', '1/ЛИНИЯ')
        db.session.add(tract)
        db.session.flush()
        tract = Tracts('1.44+1.937', 'DWDM', '', 1, datetime.now(), 'A102/2', 'Линия', 'A104', '1/ЛИНИЯ')
        db.session.add(tract)
        db.session.flush()
        tract = Tracts('1.101', 'E1', '', 1, datetime.now(), 'A20/15', 'A22/3', '1', '1')
        db.session.add(tract)
        db.session.flush()
        tract = Tracts('1.102', 'E1', '', 1, datetime.now(), 'A20/16', 'A22/4', '1', '1')
        db.session.add(tract)
        db.session.flush()
        tract = Tracts('1.103', 'E1', '', 1, datetime.now(), 'A21/15', 'A22/3', '1', '2')
        db.session.add(tract)
        db.session.flush()
        tract = Tracts('1.104', 'E1', '', 1, datetime.now(), 'A21/16', 'A22/4', '1', '2')
        db.session.add(tract)
        db.session.flush()
        tract = Tracts('1.105', 'Ethernet', '', 1, datetime.now(), 'A23', 'A24/1', '1', '1')
        db.session.add(tract)
        db.session.flush()
        reservDict['1.105'] = tract.id
        tract = Tracts('1.106', 'Ethernet', '', 1, datetime.now(), 'A23', 'A25/1', '2', '1')
        db.session.add(tract)
        db.session.flush()
        reservDict['1.106'] = tract.id
        reserv = ReserveTracts(reservDict['1.105'], reservDict['1.106'])
        db.session.add(reserv)
        tract = Tracts('1.107', 'Ethernet', '', 1, datetime.now(), 'A23', 'A26/1', '25', '3')
        db.session.add(tract)
        db.session.flush()
        tract = Tracts('1.108', 'Ethernet', '', 1, datetime.now(), 'A23', 'A27/1', '26', '3')
        db.session.add(tract)
        db.session.flush()
        tract = Tracts('1.109', 'E1', '', 1, datetime.now(), 'A22/8', 'A24/1', '1', '2')
        db.session.add(tract)
        db.session.flush()
        reservDict['1.109'] = tract.id
        tract = Tracts('1.110', 'E1', '', 1, datetime.now(), 'A22/9', 'A25/1', '1', '2')
        db.session.add(tract)
        db.session.flush()
        reservDict['1.110'] = tract.id
        reserv = ReserveTracts(reservDict['1.109'], reservDict['1.110'])
        db.session.add(reserv)
        tract = Tracts('1.111', 'E1', '', 1, datetime.now(), 'A22/8', 'A24/1', '2', '3')
        db.session.add(tract)
        db.session.flush()
        reservDict['1.111'] = tract.id
        tract = Tracts('1.112', 'E1', '', 1, datetime.now(), 'A22/9', 'A25/1', '2', '3')
        db.session.add(tract)
        db.session.flush()
        reservDict['1.112'] = tract.id
        reserv = ReserveTracts(reservDict['1.111'], reservDict['1.112'])
        db.session.add(reserv)
        tract = Tracts('1.113', 'E1', '', 1, datetime.now(), 'A22/13', 'A26/1', '1', '1')
        db.session.add(tract)
        db.session.flush()
        tract = Tracts('1.114', 'E1', '', 1, datetime.now(), 'A22/13', 'A27/1', '2', '1')
        db.session.add(tract)
        db.session.flush()
        tract = Tracts('1.115', 'E1', '', 1, datetime.now(), 'A22/14', 'A27/1', '1', '2')
        db.session.add(tract)
        db.session.flush()
        tract = Tracts('1.116', 'E1', '', 1, datetime.now(), 'A22/14', 'A27/1', '1', '2')
        db.session.add(tract)
        db.session.flush()
        tract = Tracts('1.117', 'E1', '', 1, datetime.now(), 'A22/7', 'A26/1', '2', '2')
        db.session.add(tract)
        db.session.flush()
        tract = Tracts('1.118', 'E1', '', 1, datetime.now(), 'A22/7', 'A26/1', '1', '8')
        db.session.add(tract)
        db.session.flush()
        tract = Tracts('1.119+1.912+1.239', 'DWDM', '', 1, datetime.now(), 'A24/1', 'A36/1', 'Линия', 'Линия')
        db.session.add(tract)
        db.session.flush()
        tract = Tracts('1.120+1.913+1.240', 'DWDM', '', 1, datetime.now(), 'A25/1', 'A37/1', 'Линия', 'Линия')
        db.session.add(tract)
        db.session.flush()
        tract = Tracts('1.121+1.914+1.413', 'DWDM', '', 1, datetime.now(), 'A26/1', 'A72/1', 'Линия', 'Линия')
        db.session.add(tract)
        db.session.flush()
        tract = Tracts('1.122+1.915+1.513', 'DWDM', '', 1, datetime.now(), 'A27/1', 'A82/1', 'Линия', 'Линия')
        db.session.add(tract)
        db.session.flush()
        tract = Tracts('1.201', 'E1', '', 1, datetime.now(), 'A30/15', 'A33/3', '1', '1')
        db.session.add(tract)
        db.session.flush()
        tract = Tracts('1.202', 'E1', '', 1, datetime.now(), 'A30/16', 'A33/4', '1', '1')
        db.session.add(tract)
        db.session.flush()
        tract = Tracts('1.203', 'E1', '', 1, datetime.now(), 'A30/15', 'A32/3', '2', '1')
        db.session.add(tract)
        db.session.flush()
        tract = Tracts('1.204', 'E1', '', 1, datetime.now(), 'A30/16', 'A32/4', '2', '1')
        db.session.add(tract)
        db.session.flush()
        tract = Tracts('1.205', 'E1', '', 1, datetime.now(), 'A31/15', 'A33/3', '1', '2')
        db.session.add(tract)
        db.session.flush()
        tract = Tracts('1.206', 'E1', '', 1, datetime.now(), 'A31/16', 'A33/4', '1', '2')
        db.session.add(tract)
        db.session.flush()
        tract = Tracts('1.207', 'E1', '', 1, datetime.now(), 'A31/15', 'A32/3', '2', '2')
        db.session.add(tract)
        db.session.flush()
        tract = Tracts('1.208', 'E1', '', 1, datetime.now(), 'A31/16', 'A32/4', '2', '2')
        db.session.add(tract)
        db.session.flush()
        tract = Tracts('1.209', 'Ethernet', '', 1, datetime.now(), 'A34', 'A35', '25', '25')
        db.session.add(tract)
        db.session.flush()
        tract = Tracts('1.210', 'Ethernet', '', 1, datetime.now(), 'A34', 'A35', '26', '26')
        db.session.add(tract)
        db.session.flush()
        tract = Tracts('1.211', 'Ethernet', '', 1, datetime.now(), 'A35', 'A38.1', '1', '1')
        db.session.add(tract)
        db.session.flush()
        reservDict['1.211'] = tract.id
        tract = Tracts('1.212', 'Ethernet', '', 1, datetime.now(), 'A35', 'A39.1', '2', '1')
        db.session.add(tract)
        db.session.flush()
        reservDict['1.212'] = tract.id
        reserv = ReserveTracts(reservDict['1.211'], reservDict['1.212'])
        db.session.add(reserv)
        tract = Tracts('1.213', 'Ethernet', '', 1, datetime.now(), 'A35', 'A40/1', '3', '1')
        db.session.add(tract)
        db.session.flush()
        reservDict['1.213'] = tract.id
        tract = Tracts('1.214', 'Ethernet', '', 1, datetime.now(), 'A35', 'A41/1', '4', '1')
        db.session.add(tract)
        db.session.flush()
        reservDict['1.214'] = tract.id
        reserv = ReserveTracts(reservDict['1.213'], reservDict['1.214'])
        db.session.add(reserv)
        tract = Tracts('1.215', 'Ethernet', '', 1, datetime.now(), 'A35', 'A36/1', '5', '1')
        db.session.add(tract)
        db.session.flush()
        reservDict['1.215'] = tract.id
        tract = Tracts('1.216', 'Ethernet', '', 1, datetime.now(), 'A35', 'A37/1', '6', '1')
        db.session.add(tract)
        db.session.flush()
        reservDict['1.216'] = tract.id
        reserv = ReserveTracts(reservDict['1.215'], reservDict['1.216'])
        db.session.add(reserv)
        tract = Tracts('1.217', 'E1', '', 1, datetime.now(), 'A33/9', 'A38.1', '1', '2')
        db.session.add(tract)
        db.session.flush()
        reservDict['1.217'] = tract.id
        tract = Tracts('1.218', 'E1', '', 1, datetime.now(), 'A33/9', 'A39.1', '2', '2')
        db.session.add(tract)
        db.session.flush()
        reservDict['1.218'] = tract.id
        reserv = ReserveTracts(reservDict['1.217'], reservDict['1.218'])
        db.session.add(reserv)
        tract = Tracts('1.219', 'E1', '', 1, datetime.now(), 'A33/9', 'A40/1', '3', '2')
        db.session.add(tract)
        db.session.flush()
        reservDict['1.219'] = tract.id
        tract = Tracts('1.220', 'E1', '', 1, datetime.now(), 'A33/9', 'A41/1', '4', '2')
        db.session.add(tract)
        db.session.flush()
        reservDict['1.220'] = tract.id
        reserv = ReserveTracts(reservDict['1.219'], reservDict['1.220'])
        db.session.add(reserv)
        tract = Tracts('1.221', 'E1', '', 1, datetime.now(), 'A33/10', 'A38.1', '1', '3')
        db.session.add(tract)
        db.session.flush()
        reservDict['1.221'] = tract.id
        tract = Tracts('1.222', 'E1', '', 1, datetime.now(), 'A33/10', 'A39.1', '2', '3')
        db.session.add(tract)
        db.session.flush()
        reservDict['1.222'] = tract.id
        reserv = ReserveTracts(reservDict['1.221'], reservDict['1.222'])
        db.session.add(reserv)
        tract = Tracts('1.223', 'E1', '', 1, datetime.now(), 'A33/10', 'A40/1', '3', '3')
        db.session.add(tract)
        db.session.flush()
        reservDict['1.223'] = tract.id
        tract = Tracts('1.224', 'E1', '', 1, datetime.now(), 'A33/10', 'A41/1', '4', '3')
        db.session.add(tract)
        db.session.flush()
        reservDict['1.224'] = tract.id
        reserv = ReserveTracts(reservDict['1.223'], reservDict['1.224'])
        db.session.add(reserv)
        tract = Tracts('1.225', 'E1', '', 1, datetime.now(), 'A33/13', 'A42/1', '1', '1')
        db.session.add(tract)
        db.session.flush()
        tract = Tracts('1.226', 'E1', '', 1, datetime.now(), 'A33/13', 'A43/1', '2', '1')
        db.session.add(tract)
        db.session.flush()
        tract = Tracts('1.227', 'E1', '', 1, datetime.now(), 'A33/14', 'A43/1', '1', '2')
        db.session.add(tract)
        db.session.flush()
        tract = Tracts('1.228', 'E1', '', 1, datetime.now(), 'A33/14', 'A42/1', '2', '2')
        db.session.add(tract)
        db.session.flush()
        tract = Tracts('1.229', 'E1', '', 1, datetime.now(), 'A33/7', 'A36/1', '3', '2')
        db.session.add(tract)
        db.session.flush()
        reservDict['1.229'] = tract.id
        tract = Tracts('1.230', 'E1', '', 1, datetime.now(), 'A33/7', 'A37/1', '4', '2')
        db.session.add(tract)
        db.session.flush()
        reservDict['1.230'] = tract.id
        reserv = ReserveTracts(reservDict['1.229'], reservDict['1.230'])
        db.session.add(reserv)
        tract = Tracts('1.231', 'E1', '', 1, datetime.now(), 'A33/8', 'A36/1', '1', '3')
        db.session.add(tract)
        db.session.flush()
        reservDict['1.231'] = tract.id
        tract = Tracts('1.232', 'E1', '', 1, datetime.now(), 'A33/8', 'A37/1', '2', '3')
        db.session.add(tract)
        db.session.flush()
        reservDict['1.232'] = tract.id
        reserv = ReserveTracts(reservDict['1.231'], reservDict['1.232'])
        db.session.add(reserv)
        tract = Tracts('1.233+1.920+1.606', 'E1', '', 1, datetime.now(), 'A33/7', 'A90/2', '1', '3')
        db.session.add(tract)
        db.session.flush()
        tract = Tracts('1.234+1.921+1.616', 'E1', '', 1, datetime.now(), 'A33/7', 'A93/2', '2', '3')
        db.session.add(tract)
        db.session.flush()
        tract = Tracts('1.237', 'DWDM', '', 1, datetime.now(), 'A38.1', 'A38.2/1', 'Линия', 'Общий')
        db.session.add(tract)
        db.session.flush()
        tract = Tracts('1.238', 'DWDM', '', 1, datetime.now(), 'A39.1', 'A39.2/1', 'Линия', 'Общий')
        db.session.add(tract)
        db.session.flush()
        tract = Tracts('1.249+1.916+1.325', 'DWDM', '', 1, datetime.now(), 'A40/1', 'A58/1', 'Линия', 'Линия')
        db.session.add(tract)
        db.session.flush()
        tract = Tracts('1.250+1.917+1.326', 'DWDM', '', 1, datetime.now(), 'A41/1', 'A59/1', 'Линия', 'Линия')
        db.session.add(tract)
        db.session.flush()
        tract = Tracts('1.251+1.918+1.608', 'DWDM', '', 1, datetime.now(), 'A42/1', 'A91/1', 'Линия', 'Линия')
        db.session.add(tract)
        db.session.flush()
        tract = Tracts('1.252+1.919+1.620', 'DWDM', '', 1, datetime.now(), 'A43/1', 'A94/1', 'Линия', 'Линия')
        db.session.add(tract)
        db.session.flush()
        tract = Tracts('1.253+1.922+1.712', 'E1', '', 1, datetime.now(), 'A38.1', 'A110/16', '7', '1')
        db.session.add(tract)
        db.session.flush()
        tract = Tracts('1.254+1.923+1.704', 'E2', '', 1, datetime.now(), 'A38.1', 'A107/2', '8', 'SFP2')
        db.session.add(tract)
        db.session.flush()
        tract = Tracts('1.301', 'E1', '', 1, datetime.now(), 'A50/15', 'A53/3', '1', '1')
        db.session.add(tract)
        db.session.flush()
        tract = Tracts('1.302', 'E1', '', 1, datetime.now(), 'A50/16', 'A53/4', '1', '1')
        db.session.add(tract)
        db.session.flush()
        tract = Tracts('1.303', 'E1', '', 1, datetime.now(), 'A50/15', 'A52/3', '2', '1')
        db.session.add(tract)
        db.session.flush()
        tract = Tracts('1.304', 'E1', '', 1, datetime.now(), 'A50/16', 'A52/4', '2', '1')
        db.session.add(tract)
        db.session.flush()
        tract = Tracts('1.305', 'E1', '', 1, datetime.now(), 'A50/15', 'A53/3', '1', '2')
        db.session.add(tract)
        db.session.flush()
        tract = Tracts('1.306', 'E1', '', 1, datetime.now(), 'A51/16', 'A53/4', '1', '2')
        db.session.add(tract)
        db.session.flush()
        tract = Tracts('1.307', 'E1', '', 1, datetime.now(), 'A51/15', 'A52/3', '2', '2')
        db.session.add(tract)
        db.session.flush()
        tract = Tracts('1.308', 'E1', '', 1, datetime.now(), 'A51/16', 'A52/4', '2', '2')
        db.session.add(tract)
        db.session.flush()
        tract = Tracts('1.309', 'Ethernet', '', 1, datetime.now(), 'A54', 'A55', '25', '25')
        db.session.add(tract)
        db.session.flush()
        tract = Tracts('1.310', 'Ethernet', '', 1, datetime.now(), 'A54', 'A55', '26', '26')
        db.session.add(tract)
        db.session.flush()
        tract = Tracts('1.311', 'Ethernet','', 1, datetime.now(), 'A55', 'A56/1', '1', '1')
        db.session.add(tract)
        db.session.flush()
        reservDict['1.311'] = tract.id
        tract = Tracts('1.312', 'Ethernet','', 1, datetime.now(), 'A55', 'A57/1', '2', '1')
        db.session.add(tract)
        db.session.flush()
        reservDict['1.312'] = tract.id
        reserv = ReserveTracts(reservDict['1.311'], reservDict['1.312'])
        db.session.add(reserv)
        tract = Tracts('1.313', 'Ethernet','', 1, datetime.now(), 'A55', 'A58/1', '3', '1')
        db.session.add(tract)
        db.session.flush()
        reservDict['1.313'] = tract.id
        tract = Tracts('1.314', 'Ethernet', '', 1, datetime.now(), 'A55', 'A59/1', '4', '1')
        db.session.add(tract)
        db.session.flush()
        reservDict['1.314'] = tract.id
        reserv = ReserveTracts(reservDict['1.313'], reservDict['1.314'])
        db.session.add(reserv)
        tract = Tracts('1.315', 'E1', '', 1, datetime.now(), 'A53/7', 'A56/1', '1', '2')
        db.session.add(tract)
        db.session.flush()
        reservDict['1.315'] = tract.id
        tract = Tracts('1.316', 'E1', '', 1, datetime.now(), 'A53/7', 'A57/1', '2', '2')
        db.session.add(tract)
        db.session.flush()
        reservDict['1.316'] = tract.id
        reserv = ReserveTracts(reservDict['1.315'], reservDict['1.316'])
        db.session.add(reserv)
        tract = Tracts('1.317', 'E1', '', 1, datetime.now(), 'A53/7', 'A58/1', '3', '2')
        db.session.add(tract)
        db.session.flush()
        reservDict['1.317'] = tract.id
        tract = Tracts('1.318', 'E1', '', 1, datetime.now(), 'A53/7', 'A59/1', '4', '2')
        db.session.add(tract)
        db.session.flush()
        reservDict['1.318'] = tract.id
        reserv = ReserveTracts(reservDict['1.317'], reservDict['1.318'])
        db.session.add(reserv)
        tract = Tracts('1.319', 'E1', '', 1, datetime.now(), 'A53/8', 'A56/1', '1', '3')
        db.session.add(tract)
        db.session.flush()
        reservDict['1.319'] = tract.id
        tract = Tracts('1.320', 'E1', '', 1, datetime.now(), 'A53/8', 'A57/1', '2', '3')
        db.session.add(tract)
        db.session.flush()
        reservDict['1.320'] = tract.id
        reserv = ReserveTracts(reservDict['1.319'], reservDict['1.320'])
        db.session.add(reserv)
        tract = Tracts('1.321', 'E1', '', 1, datetime.now(), 'A53/8', 'A58/1', '3', '3')
        db.session.add(tract)
        db.session.flush()
        reservDict['1.321'] = tract.id
        tract = Tracts('1.322', 'E1', '', 1, datetime.now(), 'A53/8', 'A59/1', '4', '3')
        db.session.add(tract)
        db.session.flush()
        reservDict['1.322'] = tract.id
        reserv = ReserveTracts(reservDict['1.321'], reservDict['1.322'])
        db.session.add(reserv)
        tract = Tracts('1.327', 'E1', '', 1, datetime.now(), 'A53/3', 'A62/1', '3', '1')
        db.session.add(tract)
        db.session.flush()
        tract = Tracts('1.328', 'E1', '', 1, datetime.now(), 'A53/4', 'A62/2', '3', '1')
        db.session.add(tract)
        db.session.flush()
        tract = Tracts('1.329', 'E1', '', 1, datetime.now(), 'A53/3', 'A62/1', '4', '2')
        db.session.add(tract)
        db.session.flush()
        tract = Tracts('1.330', 'E1', '', 1, datetime.now(), 'A53/4', 'A62/2', '4', '2')
        db.session.add(tract)
        db.session.flush()
        tract = Tracts('1.401', 'Ethernet', '', 1, datetime.now(), 'A71/4', 'A72/1', '1', '3')
        db.session.add(tract)
        db.session.flush()
        tract = Tracts('1.402', 'Ethernet', '', 1, datetime.now(), 'A71/4', 'A72/2', '2', '3')
        db.session.add(tract)
        db.session.flush()
        tract = Tracts('1.403', 'Ethernet', '', 1, datetime.now(), 'A71/5', 'A72/3', '1', '3')
        db.session.add(tract)
        db.session.flush()
        tract = Tracts('1.405', 'E1', '', 1, datetime.now(), 'A70/11', 'A72/1', '1', '1')
        db.session.add(tract)
        db.session.flush()
        tract = Tracts('1.406', 'E1', '', 1, datetime.now(), 'A70/11', 'A72/2', '2', '1')
        db.session.add(tract)
        db.session.flush()
        tract = Tracts('1.407', 'E1', '', 1, datetime.now(), 'A70/12', 'A72/2', '1', '4')
        db.session.add(tract)
        db.session.flush()
        tract = Tracts('1.408', 'E1', '', 1, datetime.now(), 'A70/12', 'A72/3', '2', '4')
        db.session.add(tract)
        db.session.flush()
        tract = Tracts('1.409', 'E1', '', 1, datetime.now(), 'A70/12', 'A72/1', '4', '8')
        db.session.add(tract)
        db.session.flush()
        tract = Tracts('1.411+1.926+1.605', 'E1', '', 1, datetime.now(), 'A90/1', 'A53/3', '3', '3')
        db.session.add(tract)
        db.session.flush()
        tract = Tracts('1.412', 'E1', '', 1, datetime.now(), 'A72/1', 'A72/2', '2', '2')
        db.session.add(tract)
        db.session.flush()
        tract = Tracts('1.414+1.924+1.515', 'DWDM', '', 1, datetime.now(), 'A72/2', 'A82/3', 'Линия', 'Линия')
        db.session.add(tract)
        db.session.flush()
        tract = Tracts('1.415+1.925+1.514', 'DWDM', '', 1, datetime.now(), 'A72/3', 'A82/2', 'Линия', 'Линия')
        db.session.add(tract)
        db.session.flush()
        tract = Tracts('1.501', 'Ethernet', '', 1, datetime.now(), 'A81/1', 'A82/1', '1', '3')
        db.session.add(tract)
        db.session.flush()
        tract = Tracts('1.502', 'Ethernet', '', 1, datetime.now(), 'A81/4', 'A82/2', '2', '3')
        db.session.add(tract)
        db.session.flush()
        tract = Tracts('1.503', 'Ethernet', '', 1, datetime.now(), 'A81/5', 'A82/3', '1', '3')
        db.session.add(tract)
        db.session.flush()
        tract = Tracts('1.505', 'E1', '', 1, datetime.now(), 'A80/11', 'A82/1', '1', '2')
        db.session.add(tract)
        db.session.flush()
        tract = Tracts('1.506', 'E1', '', 1, datetime.now(), 'A80/11', 'A82/3', '2', '2')
        db.session.add(tract)
        db.session.flush()
        tract = Tracts('1.507', 'E1', '', 1, datetime.now(), 'A80/12', 'A82/2', '1', '4')
        db.session.add(tract)
        db.session.flush()
        tract = Tracts('1.508', 'E1', '', 1, datetime.now(), 'A80/12', 'A82/3', '2', '4')
        db.session.add(tract)
        db.session.flush()
        tract = Tracts('1.509', 'E1', '', 1, datetime.now(), 'A80/12', 'A82/1', '4', '8')
        db.session.add(tract)
        db.session.flush()
        tract = Tracts('1.511+1,927+1,615', 'E1', '', 1, datetime.now(), 'A80/12', 'A93/1', '3', '3')
        db.session.add(tract)
        db.session.flush()
        tract = Tracts('1.512', 'E1', '', 1, datetime.now(), 'A50/15', 'A82/3', '1', '1')
        db.session.add(tract)
        db.session.flush()
        tract = Tracts('1.601', 'E1', '', 1, datetime.now(), 'A50/15', 'A91/1', '1', '1')
        db.session.add(tract)
        db.session.flush()
        tract = Tracts('1.602', 'E1', '', 1, datetime.now(), 'A50/15', 'A91/2', '1', '1')
        db.session.add(tract)
        db.session.flush()
        tract = Tracts('1.603', 'E1', '', 1, datetime.now(), 'A50/15', 'A91/2', '2', '3')
        db.session.add(tract)
        db.session.flush()
        tract = Tracts('1.604', 'E1', '', 1, datetime.now(), 'A50/15', 'A91/3', '2', '3')
        db.session.add(tract)
        db.session.flush()
        tract = Tracts('1.607', 'E1', '', 1, datetime.now(), 'A50/15', 'A91/2', '2', '2')
        db.session.add(tract)
        db.session.flush()
        tract = Tracts('1.609+1,928+1,622', 'DWDM', '', 1, datetime.now(), 'A91/2', 'A94/3', 'Линия', 'Линия')
        db.session.add(tract)
        db.session.flush()
        tract = Tracts('1.610+19,929+1,621', 'DWDM', '', 1, datetime.now(), 'A91/3', 'A94/2', 'Линия', 'Линия')
        db.session.add(tract)
        db.session.flush()
        tract = Tracts('1.611', 'E1', '', 1, datetime.now(), 'A93/1', 'A94/1', '1', '2')
        db.session.add(tract)
        db.session.flush()
        tract = Tracts('1.612', 'E1', '', 1, datetime.now(), 'A93/2', 'A94/3', '1', '2')
        db.session.add(tract)
        db.session.flush()
        tract = Tracts('1.613', 'E1', '', 1, datetime.now(), 'A93/2', 'A94/2', '2', '3')
        db.session.add(tract)
        db.session.flush()
        tract = Tracts('1.614', 'E1', '', 1, datetime.now(), 'A93/2', 'A94/3', '2', '3')
        db.session.add(tract)
        db.session.flush()
        tract = Tracts('1.619', 'E1', '', 1, datetime.now(), 'A94/1', 'A94/3', '1', '1')
        db.session.add(tract)
        db.session.flush()
        tract = Tracts('1.701', 'Ethernet', '', 1, datetime.now(), 'A105', 'A104', 'П1', '1/1470нм')
        db.session.add(tract)
        db.session.flush()
        tract = Tracts('1.702', 'Ethernet', '', 1, datetime.now(), 'A105', 'A104', 'П2', '2/1470нм')
        db.session.add(tract)
        db.session.flush()
        tract = Tracts('1.703', 'E3', '', 1, datetime.now(), 'A107/1', 'A104', 'SFP2', '1/1550нм')
        db.session.add(tract)
        db.session.flush()
        tract = Tracts('2.29', 'Ethernet', '', 1, datetime.now(), 'A3/14', 'A6', '1', '9')
        db.session.add(tract)
        db.session.flush()
        tract = Tracts('2.30', 'Ethernet', '', 1, datetime.now(), 'A3/14', 'A6', '2', '10')
        db.session.add(tract)
        db.session.flush()
        tract = Tracts('2.31', 'Ethernet', '', 1, datetime.now(), 'A3/15', 'A6', '1', '11')
        db.session.add(tract)
        db.session.flush()
        tract = Tracts('2.32', 'Ethernet', '', 1, datetime.now(), 'A3/15', 'A6', '2', '12')
        db.session.add(tract)
        db.session.flush()
        tract = Tracts('2.33', 'Ethernet', '', 1, datetime.now(), 'A3/16', 'A6', '1', '13')
        db.session.add(tract)
        db.session.flush()
        tract = Tracts('2.34', 'Ethernet', '', 1, datetime.now(), 'A3/16', 'A6', '2', '14')
        db.session.add(tract)
        db.session.flush()
        tract = Tracts('2.43', 'E1', '', 1, datetime.now(), 'A4/11', 'A11', '1', '')
        db.session.add(tract)
        db.session.flush()
        tract = Tracts('2.44', 'E1', '', 1, datetime.now(), 'A4/11', 'A11', '2', '')
        db.session.add(tract)
        db.session.flush()
        tract = Tracts('2.45', 'E1', '', 1, datetime.now(), 'A4/11', 'A11', '3', '')
        db.session.add(tract)
        db.session.flush()
        tract = Tracts('2.46', 'E1', '', 1, datetime.now(), 'A4/11', 'A11', '4', '')
        db.session.add(tract)
        db.session.flush()
        tract = Tracts('2.47', 'Ethernet', '', 1, datetime.now(), 'A5', 'A14', '9', '1')
        db.session.add(tract)
        db.session.flush()
        tract = Tracts('2.48', 'Ethernet', '', 1, datetime.now(), 'A5', 'A14', '10', '2')
        db.session.add(tract)
        db.session.flush()
        tract = Tracts('2.49', 'Ethernet', '', 1, datetime.now(), 'A5', 'A1/18', '17', 'ETH 1')
        db.session.add(tract)
        db.session.flush()
        tract = Tracts('2.50', 'Ethernet', '', 1, datetime.now(), 'A5', 'A2/18', '18', 'ETH 1')
        db.session.add(tract)
        db.session.flush()
        tract = Tracts('2.51', 'Ethernet', '', 1, datetime.now(), 'A5', 'A11', '19', 'Упр')
        db.session.add(tract)
        db.session.flush()
        tract = Tracts('2.52', 'Ethernet', '', 1, datetime.now(), 'A5', 'A12', '20', 'Упр')
        db.session.add(tract)
        db.session.flush()
        tract = Tracts('2.53', 'Ethernet', '', 1, datetime.now(), 'A5', 'ПМ-11', '21', 'ETHERNET')
        db.session.add(tract)
        db.session.flush()
        tract = Tracts('2.54', 'Ethernet', '', 1, datetime.now(), 'A6', 'A3/18', '17', 'ETH 1')
        db.session.add(tract)
        db.session.flush()
        tract = Tracts('2.55', 'Ethernet', '', 1, datetime.now(), 'A6', 'A4/18', '18', 'ETH 1')
        db.session.add(tract)
        db.session.flush()
        tract = Tracts('2.56', 'Ethernet', '', 1, datetime.now(), 'A6', 'A7', '19', 'Сеть 1')
        db.session.add(tract)
        db.session.flush()
        tract = Tracts('2.57', 'Ethernet', '', 1, datetime.now(), 'A6', 'A8', '20', 'Сеть 1')
        db.session.add(tract)
        db.session.flush()
        tract = Tracts('2.58', 'Ethernet', '', 1, datetime.now(), 'A6', 'A9', '21', 'Сеть 1')
        db.session.add(tract)
        db.session.flush()
        tract = Tracts('2.59', 'Ethernet', '', 1, datetime.now(), 'A6', 'A10', '22', 'Сеть 1')
        db.session.add(tract)
        db.session.flush()
        tract = Tracts('2.60', '--', '', 1, datetime.now(), 'A3/17', 'A12', 'Синх', 'MSYNC')
        db.session.add(tract)
        db.session.flush()
        tract = Tracts('2.61', '--', '', 1, datetime.now(), 'A4/17', 'A12', 'Синх', 'MSYNC')
        db.session.add(tract)
        db.session.flush()
        tract = Tracts('2.52', 'Ethernet', '', 1, datetime.now(), 'A6', 'A12', '23', 'MLANP')
        db.session.add(tract)
        db.session.flush()
        tract = Tracts('2.63', 'Ethernet', '', 1, datetime.now(), 'A5', 'A13', '11', 'Блок служебной связи')
        db.session.add(tract)
        db.session.flush()
        tract = Tracts('2.87', 'Ethernet', '', 1, datetime.now(), 'A5', 'ПМ-11/шк. 2', '22', 'ETHERNET')
        db.session.add(tract)
        db.session.flush()
        tract = Tracts('2.133', 'Ethernet', '', 1, datetime.now(), 'A23', 'A29', '9', 'LAN')
        db.session.add(tract)
        db.session.flush()
        tract = Tracts('2.134', 'Ethernet', '', 1, datetime.now(), 'A23', 'A28', '10', 'Блок служебной связи')
        db.session.add(tract)
        db.session.flush()
        tract = Tracts('2.135', 'Ethernet', '', 1, datetime.now(), 'A23', 'A20/18', '17', 'ETH 1')
        db.session.add(tract)
        db.session.flush()
        tract = Tracts('2.136', 'Ethernet', '', 1, datetime.now(), 'A23', 'A21/18', '18', 'ETH 1')
        db.session.add(tract)
        db.session.flush()
        tract = Tracts('2.137', 'Ethernet', '', 1, datetime.now(), 'A23', 'A22/18', '19', 'ETH 1')
        db.session.add(tract)
        db.session.flush()
        tract = Tracts('2.138', 'Ethernet', '', 1, datetime.now(), 'A23', 'A24', '20', 'Сеть 1')
        db.session.add(tract)
        db.session.flush()
        tract = Tracts('2.139', 'Ethernet', '', 1, datetime.now(), 'A23', 'A25', '21', 'Сеть 1')
        db.session.add(tract)
        db.session.flush()
        tract = Tracts('2.140', 'Ethernet', '', 1, datetime.now(), 'A23', 'A26', '22', 'Сеть 1')
        db.session.add(tract)
        db.session.flush()
        tract = Tracts('2.141', 'Ethernet', '', 1, datetime.now(), 'A23', 'A27', '23', 'Сеть 1')
        db.session.add(tract)
        db.session.flush()
        tract = Tracts('2.142', 'Ethernet', '', 1, datetime.now(), 'A23', 'ПМ-11', '24', 'ETHERNET')
        db.session.add(tract)
        db.session.flush()
        tract = Tracts('2.143', 'Ethernet', '', 1, datetime.now(), 'A23', 'A22/16', '11', 'WAN1')
        db.session.add(tract)
        db.session.flush()
        tract = Tracts('2.229', 'Ethernet', '', 1, datetime.now(), 'A32/14', 'A35', '1', '9')
        db.session.add(tract)
        db.session.flush()
        tract = Tracts('2.230', 'Ethernet', '', 1, datetime.now(), 'A32/14', 'A35', '2', '10')
        db.session.add(tract)
        db.session.flush()
        tract = Tracts('2.231', 'Ethernet', '', 1, datetime.now(), 'A32/15', 'A35', '1', '11')
        db.session.add(tract)
        db.session.flush()
        tract = Tracts('2.232', 'Ethernet', '', 1, datetime.now(), 'A32/16', 'A35', '2', '12')
        db.session.add(tract)
        db.session.flush()
        tract = Tracts('2.233', 'Ethernet', '', 1, datetime.now(), 'A32/16', 'A35', '1', '13')
        db.session.add(tract)
        db.session.flush()
        tract = Tracts('2.234', 'Ethernet', '', 1, datetime.now(), 'A34', 'A35', '2', '14')
        db.session.add(tract)
        db.session.flush()
        tract = Tracts('2.243', 'Ethernet', '', 1, datetime.now(), 'A34', 'ПМ-11/шк. 3', '15', 'ETHERNET')
        db.session.add(tract)
        db.session.flush()
        tract = Tracts('2.244', 'Ethernet', '', 1, datetime.now(), 'A34', 'ПМ-11/шк. 4', '16', 'ETHERNET')
        db.session.add(tract)
        db.session.flush()
        tract = Tracts('2.245', 'Ethernet', '', 1, datetime.now(), 'A34', 'A30/18', '17', 'ETH 1')
        db.session.add(tract)
        db.session.flush()
        tract = Tracts('2.246', 'Ethernet', '', 1, datetime.now(), 'A34', 'A31/18', '18', 'ETH 1')
        db.session.add(tract)
        db.session.flush()
        tract = Tracts('2.247', 'Ethernet', '', 1, datetime.now(), 'A34', 'A32/18', '19', 'ETH 1')
        db.session.add(tract)
        db.session.flush()
        tract = Tracts('2.248', 'Ethernet', '', 1, datetime.now(), 'A34', 'A33/18', '20', 'ETH 1')
        db.session.add(tract)
        db.session.flush()
        tract = Tracts('2.249', 'Ethernet', '', 1, datetime.now(), 'A34', 'A44', '21', 'Упр')
        db.session.add(tract)
        db.session.flush()
        tract = Tracts('2.253', 'Ethernet', '', 1, datetime.now(), 'A35', 'A36', '17', 'Сеть 1')
        db.session.add(tract)
        db.session.flush()
        tract = Tracts('2.254', 'Ethernet', '', 1, datetime.now(), 'A35', 'A37', '18', 'Сеть 1')
        db.session.add(tract)
        db.session.flush()
        tract = Tracts('2.255', 'Ethernet', '', 1, datetime.now(), 'A35', 'A38', '19', 'Сеть 1')
        db.session.add(tract)
        db.session.flush()
        tract = Tracts('2.256', 'Ethernet', '', 1, datetime.now(), 'A35', 'A39', '20', 'Сеть 1')
        db.session.add(tract)
        db.session.flush()
        tract = Tracts('2.257', 'Ethernet', '', 1, datetime.now(), 'A35', 'A40', '21', 'Сеть 1')
        db.session.add(tract)
        db.session.flush()
        tract = Tracts('2.258', 'Ethernet', '', 1, datetime.now(), 'A35', 'A41', '22', 'Сеть 1')
        db.session.add(tract)
        db.session.flush()
        tract = Tracts('2.259', 'Ethernet', '', 1, datetime.now(), 'A35', 'A42', '23', 'Сеть 1')
        db.session.add(tract)
        db.session.flush()
        tract = Tracts('2.260', 'Ethernet', '', 1, datetime.now(), 'A35', 'A43', '24', 'Сеть 1')
        db.session.add(tract)
        db.session.flush()
        tract = Tracts('2.261', 'Ethernet', '', 1, datetime.now(), 'A34', 'A45', '11', 'Блок служебной связи')
        db.session.add(tract)
        db.session.flush()
        tract = Tracts('2.262', 'Ethernet', '', 1, datetime.now(), 'A34', 'A46', '9', '1')
        db.session.add(tract)
        db.session.flush()
        tract = Tracts('2.263', 'Ethernet', '', 1, datetime.now(), 'A34', 'A46', '10', '2')
        db.session.add(tract)
        db.session.flush()
        tract = Tracts('2.264', 'E1', '', 1, datetime.now(), 'A33/11', 'A44', '1', '')
        db.session.add(tract)
        db.session.flush()
        tract = Tracts('2.265', 'E1', '', 1, datetime.now(), 'A33/11', 'A44', '2', '')
        db.session.add(tract)
        db.session.flush()
        tract = Tracts('2.266', 'E1', '', 1, datetime.now(), 'A33/11', 'A44', '3', '')
        db.session.add(tract)
        db.session.flush()
        tract = Tracts('2.267', 'E1', '', 1, datetime.now(), 'A33/11', 'A44', '4', '')
        db.session.add(tract)
        db.session.flush()
        tract = Tracts('2.268', 'Ethernet', '', 1, datetime.now(), 'A34', 'A33/16', '12', 'WAN1')
        db.session.add(tract)
        db.session.flush()
        db.session.add(tract)
        db.session.flush()
        tract = Tracts('2.329', 'Ethernet', '', 1, datetime.now(), 'A52/14', 'A55', '1', '9')
        db.session.add(tract)
        db.session.flush()
        tract = Tracts('2.330', 'Ethernet', '', 1, datetime.now(), 'A52/14', 'A55', '2', '10')
        db.session.add(tract)
        db.session.flush()
        tract = Tracts('2.331', 'Ethernet', '', 1, datetime.now(), 'A52/15', 'A55', '1', '11')
        db.session.add(tract)
        db.session.flush()
        tract = Tracts('2.332', 'Ethernet', '', 1, datetime.now(), 'A52/15', 'A55', '2', '12')
        db.session.add(tract)
        db.session.flush()
        tract = Tracts('2.333', 'Ethernet', '', 1, datetime.now(), 'A52/16', 'A55', '1', '13')
        db.session.add(tract)
        db.session.flush()
        tract = Tracts('2.334', 'Ethernet', '', 1, datetime.now(), 'A52/16', 'A55', '2', '14')
        db.session.add(tract)
        db.session.flush()
        tract = Tracts('2.343', 'Ethernet', '', 1, datetime.now(), 'A54', 'ПМ-11', '17', 'ETHERNET')
        db.session.add(tract)
        db.session.flush()
        tract = Tracts('2.344', 'Ethernet', '', 1, datetime.now(), 'A54', 'ПМ-11/шк. 8', '18', 'ETHERNET')
        db.session.add(tract)
        db.session.flush()
        tract = Tracts('2.345', 'Ethernet', '', 1, datetime.now(), 'A55', 'A50/18', '17', 'ETH 1')
        db.session.add(tract)
        db.session.flush()
        tract = Tracts('2.346', 'Ethernet', '', 1, datetime.now(), 'A55', 'A51/18', '18', 'ETH 1')
        db.session.add(tract)
        db.session.flush()
        tract = Tracts('2.347', 'Ethernet', '', 1, datetime.now(), 'A55', 'A52/18', '19', 'ETH 1')
        db.session.add(tract)
        db.session.flush()
        tract = Tracts('2.348', 'Ethernet', '', 1, datetime.now(), 'A55', 'A53/18', '20', 'ETH 1')
        db.session.add(tract)
        db.session.flush()
        tract = Tracts('2.349', 'Ethernet', '', 1, datetime.now(), 'A55', 'A56', '21', 'Сеть 1')
        db.session.add(tract)
        db.session.flush()
        tract = Tracts('2.350', 'Ethernet', '', 1, datetime.now(), 'A55', 'A57', '22', 'Сеть 1')
        db.session.add(tract)
        db.session.flush()
        tract = Tracts('2.351', 'Ethernet', '', 1, datetime.now(), 'A55', 'A58', '23', 'Сеть 1')
        db.session.add(tract)
        db.session.flush()
        tract = Tracts('2.352', 'Ethernet', '', 1, datetime.now(), 'A55', 'A59', '24', 'Сеть 1')
        db.session.add(tract)
        db.session.flush()
        tract = Tracts('2.353', 'Ethernet', '', 1, datetime.now(), 'A54', 'A61', '9', 'Блок служебной связи')
        db.session.add(tract)
        db.session.flush()
        tract = Tracts('2.372', 'Ethernet', '', 1, datetime.now(), 'A54', 'ПМ-11/шк. 10', '19', 'ETHERNET')
        db.session.add(tract)
        db.session.flush()
        tract = Tracts('2.413', 'Ethernet', '', 1, datetime.now(), 'A71/6', 'A73', '1', 'Блок служебной связи')
        db.session.add(tract)
        db.session.flush()
        tract = Tracts('2.414', 'Ethernet', '', 1, datetime.now(), 'A71/6', 'A70/18', '2', 'ETH 1')
        db.session.add(tract)
        db.session.flush()
        tract = Tracts('2.415', 'Ethernet', '', 1, datetime.now(), 'A71/6', 'A72', '3', 'Сеть 1')
        db.session.add(tract)
        db.session.flush()
        tract = Tracts('2.416', 'Ethernet', '', 1, datetime.now(), 'A71/6', 'ПМ-11/шк. 5', '4', 'ETHERNET')
        db.session.add(tract)
        db.session.flush()
        tract = Tracts('2.417', 'Ethernet', '', 1, datetime.now(), 'A71/7', 'A70/8', '1', '1')
        db.session.add(tract)
        db.session.flush()
        tract = Tracts('2.513', 'Ethernet', '', 1, datetime.now(), 'A81/6', 'A83', '1', 'Блок служебной связи')
        db.session.add(tract)
        db.session.flush()
        tract = Tracts('2.514', 'Ethernet', '', 1, datetime.now(), 'A81/6', 'A80/18', '2', 'ETH 1')
        db.session.add(tract)
        db.session.flush()
        tract = Tracts('2.515', 'Ethernet', '', 1, datetime.now(), 'A81/6', 'A82', '3', 'Сеть 1')
        db.session.add(tract)
        db.session.flush()
        tract = Tracts('2.516', 'Ethernet', '', 1, datetime.now(), 'A81/6', 'ПМ-11/шк. 7', '4', 'ETHERNET')
        db.session.add(tract)
        db.session.flush()
        tract = Tracts('2.517', 'Ethernet', '', 1, datetime.now(), 'A81/7', 'A80/8', '1', '1')
        db.session.add(tract)
        db.session.flush()
        tract = Tracts('2.605', 'Ethernet', '', 1, datetime.now(), 'A90', 'A92', 'ETH 1(??)', 'Блок служебной связи')
        db.session.add(tract)
        db.session.flush()
        tract = Tracts('2.614', 'Ethernet', '', 1, datetime.now(), 'A93', 'A95', 'ETH 1(??)', 'Блок служебной связи')
        db.session.add(tract)
        db.session.flush()
        tract = Tracts('РРС-тракт', '', '', 1, datetime.now(), 'A11', 'A44', 'Ствол 1', 'Ствол 1')
        db.session.add(tract)
        db.session.flush()

        db.session.commit()      
        return {'status': 'ok'}

    except Exception as ex:
        logger.error(str(ex))
        return {"status": "error", "message": str(ex)}

@app.route("/api/v1/utils/clear_stable_data/<int:check>", methods=['GET'])
def clear(check):
    try:
        if check == 17:
            HardwareState.query.delete()
            ChannelType.query.delete()
            ConnectionType.query.delete()
            TractType.query.delete()
            ChannelState.query.delete()
            ChannelIniciator.query.delete()

            DiagnosticParams.query.delete()
            TractState.query.delete()
            UserState.query.delete()
            ErrorChannel.query.delete()
            Report.query.delete()
            RowReports.query.delete()
            Tracts.query.delete()
            ReserveTracts.query.delete()
            db.session.commit()
        
        return {'status': 'ok'}
    except Exception as ex:
        logger.error(str(ex))
        return {'status': 'error'}
